### PR TITLE
Add PSR2 coding standards packages

### PR DESCRIPTION
**Pull request by bbashy**
Can run `composer build` to do CI build test.

Travis-CI can be added to run these too so you know each commit is tested.

### CODE REVIEW

**Comment by Taronyuu** [comment]
As someone that hasn't used Travis yet, isn't this a bit overkill?

**Comment by bbashy** [comment]
Oh that was just a suggestion to run the tests but isn't needed. Testing is good though. I was planning on adding some to make sure the main areas are working.

**Comment by bbashy** [comment]
Most of this is just formatting. Is this able to be merged?

**Comment by Taronyuu** [comment]
I've merged all of your commits, moving the test packages to require-dev makes it not interfering with people that just want to run the panel. 

Thank you!

**Comment by bbashy** [comment]
Yeah, not sure why I had them in non-dev originally. Thanks!

Working on 5.5 now.

**Pull request merged**
